//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit26_Plugin.Menu.ViewTools.Place_01.APUS_V315.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit26_Plugin.Menu.ViewTools.Place_01.APUS_V315.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✕ Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearLogText {
            get {
                return ResourceManager.GetString("ClearLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✗ Clear.
        /// </summary>
        internal static string ClearSelectionText {
            get {
                return ResourceManager.GetString("ClearSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement is in progress. Are you sure you want to cancel and close?.
        /// </summary>
        internal static string ConfirmCloseMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Close.
        /// </summary>
        internal static string ConfirmCloseTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyLogText {
            get {
                return ResourceManager.GetString("CopyLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command only works in project documents, not family documents..
        /// </summary>
        internal static string ErrorFamilyDocument {
            get {
                return ResourceManager.GetString("ErrorFamilyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active Revit document found..
        /// </summary>
        internal static string ErrorNoDocument {
            get {
                return ResourceManager.GetString("ErrorNoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a title block..
        /// </summary>
        internal static string ErrorNoTitleBlock {
            get {
                return ResourceManager.GetString("ErrorNoTitleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportLogText {
            get {
                return ResourceManager.GetString("ExportLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Log.
        /// </summary>
        internal static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Place Sections.
        /// </summary>
        internal static string PlaceButtonText {
            get {
                return ResourceManager.GetString("PlaceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Refresh.
        /// </summary>
        internal static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Select All.
        /// </summary>
        internal static string SelectAllText {
            get {
                return ResourceManager.GetString("SelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string StatusCancelling {
            get {
                return ResourceManager.GetString("StatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string StatusInitializing {
            get {
                return ResourceManager.GetString("StatusInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sections selected for placement..
        /// </summary>
        internal static string WarningNoSections {
            get {
                return ResourceManager.GetString("WarningNoSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APUS V315 - Auto Place Sections.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
