using System;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.ExtensibleStorage;

namespace Revit26_Plugin.LinkedDetailLineGenerator.VA003.Core.Services
{
    /// <summary>
    /// ExtensibleStorage schema + read/write for source metadata attached to every
    /// generated Detail Line, per spec Section 23. Defined now (Phase 2) even though
    /// Update/Refresh/Delete commands are future work, per Rafi's confirmation --
    /// cheaper to bake the schema in at V1 than retrofit onto already-created lines.
    ///
    /// Schema GUID is fixed and must never change across versions of this tool --
    /// changing it would orphan metadata on lines created by earlier builds.
    /// </summary>
    public class MetadataService
    {
        private static readonly Guid SchemaGuid = new Guid("A7E4F1B2-3C4D-4E5F-8A9B-1C2D3E4F5A6B");
        private const string SchemaName = "LinkedDetailLineGenerator_SourceMetadata";
        private const string VendorId = "RAFI_Revit26_Plugin";

        private const string FieldSourceLinkInstanceId = "SourceLinkInstanceId";
        private const string FieldSourceLinkDocTitle = "SourceLinkDocTitle";
        private const string FieldSourceCategory = "SourceCategory";
        private const string FieldSourceFamily = "SourceFamily";
        private const string FieldSourceType = "SourceType";
        private const string FieldSourceElementId = "SourceElementId";
        private const string FieldRepresentationMode = "RepresentationMode";
        private const string FieldMappingId = "MappingId";
        private const string FieldGeneratorVersion = "GeneratorVersion";

        public const string GeneratorVersion = "VA003";

        private Schema GetOrCreateSchema()
        {
            Schema? existing = Schema.Lookup(SchemaGuid);
            if (existing != null) return existing;

            SchemaBuilder builder = new SchemaBuilder(SchemaGuid);
            builder.SetSchemaName(SchemaName);
            builder.SetVendorId(VendorId);
            builder.SetReadAccessLevel(AccessLevel.Public);
            builder.SetWriteAccessLevel(AccessLevel.Public);

            builder.AddSimpleField(FieldSourceLinkInstanceId, typeof(long));
            builder.AddSimpleField(FieldSourceLinkDocTitle, typeof(string));
            builder.AddSimpleField(FieldSourceCategory, typeof(string));
            builder.AddSimpleField(FieldSourceFamily, typeof(string));
            builder.AddSimpleField(FieldSourceType, typeof(string));
            builder.AddSimpleField(FieldSourceElementId, typeof(long));
            builder.AddSimpleField(FieldRepresentationMode, typeof(string));
            builder.AddSimpleField(FieldMappingId, typeof(string));
            builder.AddSimpleField(FieldGeneratorVersion, typeof(string));

            return builder.Finish();
        }

        public void WriteMetadata(
            Element detailLineElement,
            long sourceLinkInstanceId,
            string sourceLinkDocTitle,
            string sourceCategory,
            string sourceFamily,
            string sourceType,
            long sourceElementId,
            string representationMode,
            Guid mappingId)
        {
            Schema schema = GetOrCreateSchema();
            Entity entity = new Entity(schema);

            entity.Set(FieldSourceLinkInstanceId, sourceLinkInstanceId);
            entity.Set(FieldSourceLinkDocTitle, sourceLinkDocTitle);
            entity.Set(FieldSourceCategory, sourceCategory);
            entity.Set(FieldSourceFamily, sourceFamily);
            entity.Set(FieldSourceType, sourceType);
            entity.Set(FieldSourceElementId, sourceElementId);
            entity.Set(FieldRepresentationMode, representationMode);
            entity.Set(FieldMappingId, mappingId.ToString());
            entity.Set(FieldGeneratorVersion, GeneratorVersion);

            detailLineElement.SetEntity(entity);
        }

        /// <summary>Reads back metadata for future Update/Delete commands. Returns
        /// null if the element has no metadata entity attached (not generated by
        /// this tool, or from an incompatible schema version).</summary>
        public SourceMetadata? ReadMetadata(Element element)
        {
            Schema? schema = Schema.Lookup(SchemaGuid);
            if (schema == null) return null;

            Entity entity = element.GetEntity(schema);
            if (!entity.IsValid()) return null;

            return new SourceMetadata
            {
                SourceLinkInstanceId = entity.Get<long>(FieldSourceLinkInstanceId),
                SourceLinkDocTitle = entity.Get<string>(FieldSourceLinkDocTitle),
                SourceCategory = entity.Get<string>(FieldSourceCategory),
                SourceFamily = entity.Get<string>(FieldSourceFamily),
                SourceType = entity.Get<string>(FieldSourceType),
                SourceElementId = entity.Get<long>(FieldSourceElementId),
                RepresentationMode = entity.Get<string>(FieldRepresentationMode),
                MappingId = entity.Get<string>(FieldMappingId),
                GeneratorVersion = entity.Get<string>(FieldGeneratorVersion),
            };
        }
    }

    /// <summary>Deserialized view of a generated Detail Line's ExtensibleStorage metadata.</summary>
    public class SourceMetadata
    {
        public long SourceLinkInstanceId { get; set; }
        public string SourceLinkDocTitle { get; set; } = string.Empty;
        public string SourceCategory { get; set; } = string.Empty;
        public string SourceFamily { get; set; } = string.Empty;
        public string SourceType { get; set; } = string.Empty;
        public long SourceElementId { get; set; }
        public string RepresentationMode { get; set; } = string.Empty;
        public string MappingId { get; set; } = string.Empty;
        public string GeneratorVersion { get; set; } = string.Empty;
    }
}
